# Config
home: false  # True : Set home as latest post, False : Set home as an index

# Header
menu:
  Archives: /archives
rss: 
background: http://reumia.github.io/hexo-theme-zzoman2015/images/background-zzoman2015.jpg # Header Background Image


# Library
fancybox: true

# Widget
# Widget List : category, tag, archive, recent_posts
widgets:
- tag
- category
- recent_posts

# Google Analytics
# ga_id: UA-149403450-1
google_analytics: UA-149403450-1

# Disqus
disqus_shortname: https://https-apeiros0-github-io.disqus.com/embed.js